controller_manager:
    ros__parameters:
        update_rate: 100  # Hz (Z1 arm doesn't need as high frequency as legs)

        z1_joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        z1_joint_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

z1_joint_state_broadcaster:
    ros__parameters:
        joints:
            - z1_joint1
            - z1_joint2
            - z1_joint3
            - z1_joint4
            - z1_joint5
            - z1_joint6

z1_joint_trajectory_controller:
    ros__parameters:
        joints:
            - z1_joint1
            - z1_joint2
            - z1_joint3
            - z1_joint4
            - z1_joint5
            - z1_joint6
        
        command_interfaces:
            - effort
        
        state_interfaces:
            - position
            - velocity
        
        state_publish_rate: 50.0
        action_monitor_rate: 20.0
