controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        z1_controller:
            type: joint_trajectory_controller/JointTrajectoryController

z1_controller:
    ros__parameters:
        joints:
            - z1_joint1
            - z1_joint2
            - z1_joint3
            - z1_joint4
            - z1_joint5
            - z1_joint6
        
        command_interfaces:
            - position
        
        state_interfaces:
            - position
            - velocity
        
        action_monitor_rate: 20.0
        allow_partial_joints_goal: false
        constraints:
            stopped_velocity_tolerance: 0.01
            goal_time: 0.0
